providers:
  file:
    directory: /etc/traefik
    watch: true # todo: keep?
  docker:
    # only expose services if they have an explicit traefik.enable=true label
    exposedByDefault: false

log:
  level: INFO

entryPoints:
  # explicitly define an entrypoint `web` on port 80
  web:
    address: ":80"
    http:
      middlewares:
        # don't sniff the mime type from the response body (will be removed in Traefik v3)
        - no-mime-sniff@file
        # enable response compression by default
        - compression@file
  # explicitly define an entrypoint `traefik` on port 8080 for ops & system management
  # - Prometheus metrics
  traefik:
    address: ":8080"

accesslog:
  filePath: "/var/log/traefik/access.log"
  format: json

metrics:
  prometheus:
    # expose metrics on the `traefik` entrypoint
    entryPoint: traefik

# todo: move /health to `web` entrypoint instead of default `traefik`, to allow health-checking from the outside?
ping: true
