# So far, we don't have credentials, so we can put REMOTE_SERVERS here
REMOTE_SERVERS:
  BNETZA:
    url: https://data.bundesnetzagentur.de/Bundesnetzagentur/SharedDocs/Downloads/DE/Sachgebiete/Energie/Unternehmen_Institutionen/E_Mobilitaet/Ladesaeulenregister.xlsx
