SHOW_MAP: false

OPENAPI_DESCRIPTION: 'This collects chargepoint data.'
OPENAPI_CONTACT_MAIL: 'mobidatabw-technik@nvbw.de'
OPENAPI_TOS: 'https://www.mobidata-bw.de/pages/nutzungsbedingungen'
OPENAPI_SERVERS:
  - url: https://api.mobidata-bw.de/ocpdb
    description: production

PUBLIC_IMAGE_PATH: /ocpdb/images

# Will be overwritten by the config.secrets.yml, but in order to have a working public setup, we maintain the public
# data sources here
SOURCES:
  bnetza_api:
  chargecloud_pforzheim:
  chargecloud_stuttgart:
  opendata_swiss:

LOGGING:
  version: 1
  formatters:
    human_readable:
      format: '%(asctime)s %(levelname)s: %(message)s'
  handlers:
    console_stdout:
      class: logging.StreamHandler
      level: INFO
      formatter: human_readable
      stream: ext://sys.stdout
    console_stderr:
      class: logging.StreamHandler
      level: ERROR
      formatter: human_readable
      stream: ext://sys.stderr
    split_log_file:
      class: webapp.common.logging.split_log_file_handler.SplitLogFileHandler
      level: INFO
      log_path: /app/logs
      formatter: human_readable
  loggers:
    webapp:
      handlers:
        - split_log_file
        - console_stdout
        - console_stderr
