name: validate

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4

    - name: make init
      run: |
        make init
    - name: validate docker-compose.yml
      run: |
        docker compose --env-file .env --env-file .env.local.example config
